Update store.js
just comment out  the redux dev tool, so dont need to be bothered about the error below:
TypeError: Cannot read property 'apply' of undefined
(anonymous function)
node_modules/redux/es/redux.js:600
  597 | 
  598 |   return funcs.reduce(function (a, b) {
  599 |     return function () {
> 600 |       return a(b.apply(void 0, arguments));
  601 |     };
  602 |   });
  603 | }
View compil